# Spiel-Controller Roboter-Steuerungs-Konfiguration
# Diese Datei ermöglicht es dir, das Verhalten anzupassen ohne neu zu kompilieren

# Roboter-Konfiguration
num_robots: 1
robot_topics:
  - "/robot_0/cmd_vel"
  # Füge weitere Topics für mehrere Roboter hinzu:
  # - "/robot_1/cmd_vel" 
  # - "/robot_2/cmd_vel"

# Controller-Zuordnung (Xbox Controller Layout)
# Achsen-Indizes hängen von deinem spezifischen Controller ab
# Xbox 360/One Controller Zuordnung:
# Linker Stick: X=0, Y=1
# Rechter Stick: X=3, Y=4
# Trigger: LT=2, RT=5
left_stick_x_axis: 0    # Seitlich links/rechts
left_stick_y_axis: 1    # Vorwärts/rückwärts
right_stick_x_axis: 3   # Rotation
robot_select_button: 0  # A-Taste (für Multi-Roboter-Steuerung)

# Bewegungs-Skalierungsfaktoren
# Passe diese Werte an um den Roboter responsiv aber nicht nervös zu machen
# Einheiten: Meter/Sekunde für linear, Radiant/Sekunde für angular
linear_scale_x: 1.0     # Max seitliche Geschwindigkeit
linear_scale_y: 1.5     # Max vorwärts/rückwärts Geschwindigkeit  
angular_scale: 2.0      # Max Rotationsgeschwindigkeit

# Sicherheits-Konfiguration
connection_timeout: 1.0  # Sekunden bis Controller-Trennung angenommen wird

# Erweiterte Einstellungen
deadzone: 0.1           # Minimale Joystick-Eingabe um zu registrieren (verhindert Drift)
publish_rate: 50.0      # Hz - wie oft Befehle gesendet werden